- hosts: inky
  remote_user: tom
  become: yes
  become_user: root
  tasks:
    - name: test connection
      ping:
    - name: copy SSH pubkey to users pubkey
      copy: src=/{{ lookup('env', 'HOME') }}/.ssh/id_rsa.pub dest=/home/tom/id_rsa.pub owner=tom group=tom
    - name: copy SSH private key to users private key
      copy: src=/{{ lookup('env', 'HOME') }}/.ssh/id_rsa dest=/home/tom/id_rsa owner=tom group=tom
