- hosts: inky
  remote_user: tom
  become: yes
  become_user: root
  tasks:
    - name: test connection
      ping:
    - name: add apt repos (emacs, docker, etc)
      apt_repository: repo='deb http://ppa.launchpad.net/ubuntu-elisp/ppa/ubuntu trusty main' state=present
    - name: apt-get update and apt-get upgrade
      apt:  update_cache=yes upgrade=safe
    - name: add main packages (git, pip, nginx, emacs, etc.)
      apt:  name={{ item }} state=latest force=yes
      with_items:
        - git
        - python-pip
        - nginx
        - python-dev
        - libpq-dev
        - postgresql-client-common
        - postgresql-client
        - emacs-snapshot
    # Copying SSH key so I can run Ansible from command line in addition to running from Vagrant
    - name: copy SSH pubkey to 'vagrant' authorized keys
      copy: src=/{{ lookup('env', 'HOME') }}/.ssh/id_rsa.pub dest=/home/vagrant/.ssh/authorized_keys2 owner=vagrant group=vagrant mode=0644
    - name: Install virtualenv
      pip:  name=virtualenv
    - name: Install virtualenvwrapper
      pip:  name=virtualenvwrapper
    # The username should definitely be a variable
    - name: create user 'tom'
      user: name=tom generate_ssh_key=yes
    - name: install .bashrc
      become: yes
      become_user: tom
      copy: src=./bashrc.sh dest=/home/tom/.bashrc
    - name: symbolic links to synced directories
      file: src=/synced dest=/home/tom/work state=link
      become: yes
      become_user: tom
    - name: install Emacs config
      git:  repo=https://github.com/mdashx/myemacs.git dest=/home/tom/.emacs.d/
      become: yes
      become_user: tom
    - name: create bin dir
      file: path=/home/tom/bin state=directory
      become: yes
      become_user: tom
    - name: get mybin
      git:  repo=https://github.com/mdashx/mybin.git dest=/home/tom/mybin
      become: yes
      become_user: tom
    - name: install mybin
      shell: cd /home/tom/mybin && bash /home/tom/mybin/install.sh
      become: yes
      become_user: tom
    - name: rm mybin dir
      file: path=/home/tom/mybin state=absent
      become: yes
      become_user: tom
    - name: install gitconfig
      copy: src=./gitconfig dest=/home/tom/.gitconfig
      
      
    # I should install my .bashrc, pull in Emacs config, install my
    # $HOME/bin, etc.  Setup Git username, etc.  Would be nice to set
    # the target machines environment variabels for Github username,
    # etc. and run the addkeys script

    # gitconfig should use a template with vars
    
