- hosts: inky
  remote_user: vagrant
  become: yes
  become_user: root
  tasks:
    - name: test connection
      ping:
    # - name: add apt repos (emacs, docker, etc)
    #   apt_repository: repo='deb http://ppa.launchpad.net/ubuntu-elisp/ppa/ubuntu trusty main' state=present
    # - name: apt-get update and apt-get upgrade
    #   apt:  update_cache=yes upgrade=safe
    - name: add main packages (git, pip, nginx, emacs, etc.)
      apt:  name={{ item }} state=latest force=yes
      with_items:
        - git
        - python-pip
        - nginx
        - python-dev
        - libpq-dev
        - postgresql-client-common
        - postgresql-client
        - emacs-snapshot
    - name: copy SSH pubkey to 'vagrant' user's authorized keys
      copy: src=/{{ lookup('env', 'HOME') }}/.ssh/id_rsa.pub dest=/home/vagrant/.ssh/authorized_keys2 owner=vagrant group=vagrant mode=0644
    - name: create user 'tom'
      user: name=tom

    # I should also copy in a deployment key here? Or maybe not, since that
    # should be project specific
    # I should install my .bashrc, pull in Emacs config, install my $HOME/bin, etc.
