- hosts: basic
  vars_prompt:
  - name: "github_user"
    prompt: "Enter Github username"
    private: no

  - name: "github_pass"
    prompt: "Enter Github password"
    private: yes
    
  roles:
    - basic
    - emacs

- hosts: python
  roles:
    - basic
    - emacs
    - python

    

