- hosts: basic
  vars_prompt:
  - name: "user"
    prompt: "Enter username"
    private: no

    
  roles:
    - setup_user
    - packages
    - emacs

- hosts: python
  roles:
    - python

- hosts: js
  vars_prompt:
  - name: "user"
    prompt: "Enter username"
    private: no

  roles:
    - js

