- hosts: basic
  vars_prompt:
  - name: "github_user"
    prompt: "Enter Github username"
    private: no

  - name: "github_pass"
    prompt: "Enter Github password"
    private: yes
    
  roles:
    - setup_user
    - packages
    # - emacs

- hosts: python
  roles:
    - python

- hosts: js
  roles:
    - js

