- name: "Add Docker apt keys"
  command: apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
  become: yes
  become_user: root

- name: "Add Docker PPA"
  apt_repository: repo='deb http://apt.dockerproject.org/repo ubuntu-xenial main' state=present
  become: yes
  become_user: root
  
- name: apt-get update and apt-get upgrade
  apt:  update_cache=yes upgrade=safe
  become: yes
  become_user: root

- name: Install packages
  apt:  name={{ item }} state=latest force=yes
  with_items:
    - mosh
    - git
    - docker-engine
    - tmux
    - curl
    - wget
    - nmap
    - python-pip
    - ispell
  become: yes
  become_user: root
    
- name: Upgrade pip
  pip: name=pip state=latest    
  become: yes
  become_user: root

- name: Install docker-py
  pip: name=docker-py
  become: yes
  become_user: root

- name: Add user to Docker group
  user: name="{{ user }}" groups=docker append=yes
  become: yes
  become_user: root
