# -*- mode: ruby -*-

# See README for additional manual operations that must be done to create the
# inky-bootstrap box.

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-16.04"
  config.vm.provision :ansible do |ansible|
    ansible.playbook = "site.yml"
    ansible.limit = "all"
  end
end
