- name: "Starting role: bash"
  debug: "msg='Starting role: bash'"

- name: "Copy bashrc"
  template: src=bashrc.sh dest="/home/{{ user }}/.bashrc"

- user: name="{{ user }}" generate_ssh_key=yes ssh_key_bits=2048 ssh_key_file=$HOME/.ssh/id_rsa
  
- shell: "bash $HOME/inky/util/add-keys-github.sh"
  environment:
    GITHUB_USER: "{{ github_user }}"
    GITHUB_PASS: "{{ github_pass }}"

- name: "Copy gitconfig"
  template: src=gitconfig dest="/home/{{ user }}/.gitconfig"

- name: "Add Docker apt keys"
  command: apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
  become: yes
  become_user: root

- name: "Add Docker PPA"
  apt_repository: repo='deb http://apt.dockerproject.org/repo ubuntu-xenial main' state=present
  become: yes
  become_user: root
  
- name: apt-get update and apt-get upgrade
  apt:  update_cache=yes upgrade=safe
  become: yes
  become_user: root

- name: Install packages (git, pip, nginx, emacs, etc.)
  apt:  name={{ item }} state=latest force=yes
  with_items:
    - git
    - docker-engine
    - tmux
    - curl
    - wget
    - nmap
    - python-pip
  become: yes
  become_user: root
    
- name: Upgrade pip
  pip: name=pip state=latest    
  become: yes
  become_user: root

- name: Install docker-py
  pip: name=docker-py
  become: yes
  become_user: root

- name: Add user to Docker group
  user: name="{{ user }}" groups=docker
  become: yes
  become_user: root
